import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import test from 'node:test';
import vm from 'node:vm';
import {Element,tick} from './test-dom.mjs';
const source=await readFile(new URL('./media.js',import.meta.url),'utf8');
function setup({reduced=false,saveData=false,reject=false}={}){
 const video=new Element(),button=new Element(),document=new Element(),window=new Element(),motion=new Element();let intersect,loads=0,plays=0;motion.matches=reduced;document.hidden=false;video.paused=true;video.attributes['aria-label']='实录';button.firstElementChild={};video.parentElement={querySelector:()=>button};const sources=[new Element(),new Element()];sources.forEach((s,i)=>s.dataset.src=i?'clip.mp4':'clip.webm');video.querySelectorAll=()=>sources;
 video.load=()=>loads++;video.pause=()=>{video.paused=true;video.emit('pause');};video.play=()=>{plays++;if(reject)return Promise.reject(Error('NotAllowedError'));video.paused=false;video.emit('play');return Promise.resolve();};document.querySelectorAll=()=>[video];
 vm.runInNewContext(source,{document,window,matchMedia:()=>motion,navigator:{connection:{saveData}},IntersectionObserver:class{constructor(fn){intersect=fn;}observe(){}disconnect(){}}});return{video,button,document,motion,sources,loads:()=>loads,plays:()=>plays,enter:()=>intersect([{target:video,isIntersecting:true}]),exit:()=>intersect([{target:video,isIntersecting:false}])};
}
test('lazy media plays in view and pauses hidden/offscreen',async()=>{const a=setup();assert.equal(a.loads(),0);a.enter();await tick();assert.equal(a.loads(),1);assert.ok(!a.video.paused);a.exit();assert.ok(a.video.paused);a.enter();await tick();assert.equal(a.loads(),1);a.document.hidden=true;a.document.emit('visibilitychange');assert.ok(a.video.paused);});
test('manual pause persists and explicit resume works',async()=>{const a=setup();a.enter();await tick();a.button.emit('click');assert.ok(a.video.paused);a.exit();a.enter();assert.ok(a.video.paused);a.button.emit('click');await tick();assert.ok(!a.video.paused);});
test('reduced motion/save-data keep poster until explicit play',async()=>{for(const c of [{reduced:true},{saveData:true}]){const a=setup(c);a.enter();assert.equal(a.loads(),0);a.button.emit('click');await tick();assert.equal(a.loads(),1);assert.ok(!a.video.paused);}});
test('autoplay refusal cannot retry-loop; media error has an explicit retry',async()=>{const a=setup({reject:true});a.enter();await tick();a.exit();a.enter();await tick();assert.equal(a.plays(),1);assert.match(a.button.attributes['aria-label'],/播放/);a.video.emit('error');assert.equal(a.button.dataset.error,'true');assert.match(a.button.attributes['aria-label'],/重新播放/);a.exit();a.enter();await tick();assert.equal(a.plays(),1);a.button.emit('click');await tick();assert.equal(a.plays(),2);});
test('all source failures expose retry even without a video error event',async()=>{const a=setup();a.enter();await tick();a.sources[0].emit('error');assert.notEqual(a.button.dataset.error,'true');a.sources[1].emit('error');assert.equal(a.button.dataset.error,'true');assert.ok(a.video.paused);a.exit();a.enter();assert.equal(a.loads(),1);a.button.emit('click');await tick();assert.equal(a.loads(),2);a.sources[0].emit('error');assert.notEqual(a.button.dataset.error,'true');});
test('an aborted old play promise cannot override a new visible playback',async()=>{const a=setup();let rejectOld; a.video.play=()=>{a.video.paused=false;return new Promise((resolve,reject)=>{rejectOld=reject;});};a.enter();a.exit();a.video.play=()=>{a.video.paused=false;return Promise.resolve();};a.enter();rejectOld(Error('AbortError'));await tick();a.exit();a.enter();await tick();assert.equal(a.video.paused,false);});
